-- Sample Books Insert Statements
-- Run these queries in phpMyAdmin to populate the library with books

INSERT INTO books (title, author, category, quantity, available, image) VALUES
('The Great Gatsby', 'F. Scott Fitzgerald', 'Fiction', 5, 5, 'gatsby.jpg'),
('To Kill a Mockingbird', 'Harper Lee', 'Fiction', 4, 4, 'mockingbird.jpg'),
('1984', 'George Orwell', 'Dystopian', 6, 6, '1984.jpg'),
('Pride and Prejudice', 'Jane Austen', 'Romance', 7, 7, 'pride.jpg'),
('The Catcher in the Rye', 'J.D. Salinger', 'Fiction', 3, 3, 'catcher.jpg'),
('Atomic Habits', 'James Clear', 'Self-Help', 8, 8, 'atomic.jpg'),
('Thinking, Fast and Slow', 'Daniel Kahneman', 'Psychology', 5, 5, 'thinking.jpg'),
('Sapiens', 'Yuval Noah Harari', 'History', 6, 6, 'sapiens.jpg'),
('The Lean Startup', 'Eric Ries', 'Business', 4, 4, 'lean.jpg'),
('Educated', 'Tara Westover', 'Biography', 5, 5, 'educated.jpg'),
('The Silent Patient', 'Alex Michaelides', 'Thriller', 4, 4, 'silent.jpg'),
('Become Your Best Self', 'Jay Shetty', 'Motivation', 7, 7, 'bestself.jpg'),
('Dune', 'Frank Herbert', 'Science Fiction', 5, 5, 'dune.jpg'),
('The Hobbit', 'J.R.R. Tolkien', 'Fantasy', 6, 6, 'hobbit.jpg'),
('Harry Potter and the Philosopher\'s Stone', 'J.K. Rowling', 'Fantasy', 10, 10, 'hp1.jpg'),
('The Lord of the Rings', 'J.R.R. Tolkien', 'Fantasy', 4, 4, 'lotr.jpg'),
('Goosebumps', 'R.L. Stine', 'Horror', 8, 8, 'goosebumps.jpg'),
('The Da Vinci Code', 'Dan Brown', 'Mystery', 5, 5, 'davinci.jpg'),
('Angels & Demons', 'Dan Brown', 'Mystery', 4, 4, 'angels.jpg'),
('Inferno', 'Dan Brown', 'Thriller', 3, 3, 'inferno.jpg'),
('The Alchemist', 'Paulo Coelho', 'Fiction', 9, 9, 'alchemist.jpg'),
('The Midnight Library', 'Matt Haig', 'Fantasy', 6, 6, 'midnight.jpg'),
('Where the Crawdads Sing', 'Delia Owens', 'Fiction', 5, 5, 'crawdads.jpg'),
('A Brief History of Time', 'Stephen Hawking', 'Science', 4, 4, 'history_time.jpg'),
('Python Crash Course', 'Eric Matthes', 'Programming', 8, 8, 'python.jpg'),
('Clean Code', 'Robert C. Martin', 'Programming', 5, 5, 'clean.jpg'),
('Design Patterns', 'Gang of Four', 'Programming', 3, 3, 'patterns.jpg'),
('The Pragmatic Programmer', 'Hunt & Thomas', 'Programming', 4, 4, 'pragmatic.jpg'),
('Code Complete', 'Steve McConnell', 'Programming', 3, 3, 'code.jpg'),
('Introduction to Algorithms', 'CLRS', 'Technology', 2, 2, 'algorithms.jpg'),
('The Girl on the Train', 'Paula Hawkins', 'Thriller', 5, 5, 'girl_train.jpg'),
('Before the Coffee Gets Cold', 'Toshikazu Kawaguchi', 'Fiction', 6, 6, 'coffee.jpg'),
('Lessons in Chemistry', 'Bonnie Garmus', 'Historical Fiction', 5, 5, 'chemistry.jpg'),
('The History of Ancient Greece', 'John Julius Norwich', 'History', 3, 3, 'greece.jpg'),
('The Science of Good Cooking', 'America\'s Test Kitchen', 'Cooking', 4, 4, 'cooking.jpg'),
('1000 Places to See Before You Die', 'Patricia Schultz', 'Travel', 3, 3, 'travel.jpg'),
('The Art of War', 'Sun Tzu', 'Philosophy', 7, 7, 'art_war.jpg'),
('Meditations', 'Marcus Aurelius', 'Philosophy', 5, 5, 'meditations.jpg'),
('On the Origin of Species', 'Charles Darwin', 'Science', 2, 2, 'species.jpg'),
('A Tale of Two Cities', 'Charles Dickens', 'Fiction', 4, 4, 'cities.jpg');
